<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="iotlab-m3.tests_xtimer_msg_receive_timeout" skips="0" tests="1" time="5.881"><properties><property name="RIOT_VERSION" value="2019.07-devel-249-g5bb49-HEAD"/></properties><testcase classname="iotlab-m3.tests_xtimer_msg_receive_timeout" file="tests/01-run.py" line="12" name="test.tests.01-run.testfunc" time="5.860898494720459"><system-out>ssh -t iotlab@saclay.iot-lab.info &apos;socat - tcp:m3-1.saclay.iot-lab.info:20000&apos;
�main(): This is RIOT! (Version: buildtest)
[START]
Message: 42
�main(): This is RIOT! (Version: buildtest)
[START]
Message: 42
Timeout!
Message: 42
Timeout!
Message: 42
Timeout!
Message: 42
Timeout!
Message: 42
Timeout!
[SUCCESS]

</system-out></testcase></testsuite>