<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="native" skips="0" tests="1" time="3.427"><testcase classname="native.tests_netstats_l2.test.tests.01-run" file="tests/01-run.py" line="13" name="testfunc" time="3.3952205181121826"><failure message="pexpect.exceptions.EOF:        Statistics for Layer 2">child = &lt;pytest_child.CustomSpawn object at 0x7fc39fb9e3c8&gt;

    def testfunc(child):
        child.sendline(&apos;ifconfig&apos;)
&gt;       child.expect(r&apos;       Statistics for Layer 2&apos;)

tests/01-run.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;pytest_child.CustomSpawn object at 0x7fc39fb9e3c8&gt;
pattern = &apos;       Statistics for Layer 2&apos;, args = (), kwargs = {}

    def expect(self, pattern, *args, **kwargs):
        # pylint:disable=arguments-differ
        try:
            return super().expect(pattern, *args, **kwargs)
        except (pexpect.TIMEOUT, pexpect.EOF) as exc:
            exc.orig_value = exc.value
            exc.value = pattern
&gt;           raise exc.with_traceback(None) from None
E           pexpect.exceptions.EOF:        Statistics for Layer 2

../../dist/tools/pytest_wrappers/test/pytest_child.py:90: EOF</failure><system-out>ifconfig
/home/cladmi/git/work/RIOT/tests/netstats_l2/bin/native/tests_netstats_l2.elf tap0 
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

/home/cladmi/git/work/RIOT/tests/netstats_l2/bin/native/tests_netstats_l2.elf: ioctl TUNSETIFF: Operation not permitted
/home/cladmi/git/work/RIOT/tests/netstats_l2/bin/native/tests_netstats_l2.elf: probably the tap interface (tap0) does not exist or is already in use
make[1]: *** [/home/cladmi/git/work/RIOT/Makefile.include:547: term] Error 1

Process already stopped
</system-out></testcase></testsuite>